const pageElements = [
  {tag: 'main', className: 'main', id: "main", parent: 'body'},
  {tag: 'h1', className: 'page-title', id: "page-title", parent: '#main'},
  {tag: 'section', className: 'text-area', id: "text-area", parent: '#main'},
  {tag: 'section', className: 'keyboard', id: "keyboard", parent: '#main'},
  {tag: 'section', className: 'comments', id: "comments", parent: '#main'},
  {tag: 'textarea', className: 'input', id: "input", parent: '#text-area'},
  {tag: 'div', className: 'keyboard__row', id: "row-1", parent: '#keyboard'},
  {tag: 'div', className: 'keyboard__row', id: "row-2", parent: '#keyboard'},
  {tag: 'div', className: 'keyboard__row', id: "row-3", parent: '#keyboard'},
  {tag: 'div', className: 'keyboard__row', id: "row-4", parent: '#keyboard'},
  {tag: 'div', className: 'keyboard__row', id: "row-5", parent: '#keyboard'},
  {tag: 'span', className: 'comments__text', id: "text-1", parent: '#comments'},
  {tag: 'span', className: 'comments__text', id: "text-2", parent: '#comments'},
]

const textContent = {
  '#page-title': 'RSS Virtual Keyboard',
  '#text-1': 'Virtual Keyboard for Windows OS',
  '#text-2': 'To switch between EN <-> RU press Shift+Alt',
};

const keys = {
  tilda: {
    position: 0,
    value: '`',
    valueRU: 'ё',
    shiftOn: '~',
    capsOnRU: 'Ё',
    row: 1,
    size: 's',
  },
  1: {
    position: 1,
    value: '1',
    shiftOn: '!',
    row: 1,
    size: 's',
  },
  2: {
    position: 2,
    value: '2',
    shiftOn: '@',
    shiftOnRU: '"',
    row: 1,
    size: 's',
  },
  3: {
    position: 3,
    value: '3',
    shiftOn: '#',
    shiftOnRU: '№',
    row: 1,
    size: 's',
  },
  4: {
    position: 4,
    value: '4',
    shiftOn: '$',
    shiftOnRU: ';',
    row: 1,
    size: 's',
  },
  5: {
    position: 5,
    value: '5',
    shiftOn: '%',
    row: 1,
    size: 's',
  },
  6: {
    position: 6,
    value: '6',
    shiftOn: '^',
    shiftOnRU: ':',
    row: 1,
    size: 's',
  },
  7: {
    position: 7,
    value: '7',
    shiftOn: '&',
    shiftOnRU: '?',
    row: 1,
    size: 's',
  },
  8: {
    position: 8,
    value: '8',
    shiftOn: '*',
    row: 1,
    size: 's',
  },
  9: {
    position: 9,
    value: '9',
    shiftOn: '(',
    row: 1,
    size: 's',
  },
  0: {
    position: 10,
    value: '0',
    shiftOn: ')',
    row: 1,
    size: 's',
  },
  minus: {
    position: 11,
    value: '-',
    shiftOn: '_',
    row: 1,
    size: 's',
  },
  equals: {
    position: 12,
    value: '=',
    shiftOn: '+',
    row: 1,
    size: 's',
  },
  backspace: {
    position: 13,
    value: 'bksp',
    shiftOn: '',
    row: 1,
    size: 'l',
  },
  tab: {
    position: 0,
    value: 'tab',
    row: 2,
    size: 'm',
  },
  q: {
    position: 1,
    value: 'q',
    capsOn: 'Q',
    valueRU: 'й',
    capsOnRU: 'Й',
    row: 2,
    size: 's',
  },
  w: {
    position: 2,
    value: 'w',
    capsOn: 'W',
    valueRU: 'ц',
    capsOnRU: 'Ц',
    row: 2,
    size: 's',
  },
  e: {
    position: 3,
    value: 'e',
    capsOn: 'E',
        valueRU: 'у',
    capsOnRU: 'У',
    row: 2,
    size: 's',
  },
  r: {
    position: 4,
    value: 'r',
    capsOn: 'R',
    valueRU: 'к',
    capsOnRU: 'К',
    row: 2,
    size: 's',
  },
  t: {
    position: 5,
    value: 't',
    capsOn: 'T',
    valueRU: 'е',
    capsOnRU: 'Е',
    row: 2,
    size: 's',
  },
  y: {
    position: 6,
    value: 'y',
    capsOn: 'Y',
    valueRU: 'н',
    capsOnRU: 'Н',
    row: 2,
    size: 's',
  },
  u: {
    position: 7,
    value: 'u',
    capsOn: 'U',
    valueRU: 'г',
    capsOnRU: 'Г',
    row: 2,
    size: 's',
  },
  i: {
    position: 8,
    value: 'i',
    capsOn: 'I',
    valueRU: 'ш',
    capsOnRU: 'Ш',
    row: 2,
    size: 's',
  },
  o: {
    position: 9,
    value: 'o',
    capsOn: 'O',
    valueRU: 'щ',
    capsOnRU: 'Щ',
    row: 2,
    size: 's',
  },
  p: {
    position: 10,
    value: 'p',
    capsOn: 'P',
    valueRU: 'з',
    capsOnRU: 'З',
    row: 2,
    size: 's',
  },
  brace_open: {
    position: 11,
    value: '[',
    shiftOn: '{',
    valueRU: 'х',
    capsOnRU: 'Х',
    row: 2,
    size: 's',
  },
  brace_close: {
    position: 12,
    value: ']',
    shiftOn: '}',
    valueRU: 'ъ',
    capsOnRU: 'Ъ',
    row: 2,
    size: 's',
  },
  slash: {
    position: 13,
    value: "|",
    shiftOn: '|',
    shiftOnRU: '/',
    row: 2,
    size: 's',
  },
  del: {
    position: 14,
    value: 'del',
    row: 2,
    size: 's',
  },
  capslock: {
    position: 0,
    value: 'capslock',
    row: 3,
    size: 'l',
  },
  a: {
    position: 1,
    value: 'a',
    capsOn: 'A',
    valueRU: 'ф',
    capsOnRU: 'Ф',
    row: 3,
    size: 's',
  },
  s: {
    position: 2,
    value: 's',
    capsOn: 'S',
    valueRU: 'ы',
    capsOnRU: 'Ы',
    row: 3,
    size: 's',
  },
  d: {
    position: 3,
    value: 'd',
    capsOn: 'D',
    valueRU: 'в',
    capsOnRU: 'В',
    row: 3,
    size: 's',
  },
  f: {
    position: 4,
    value: 'f',
    capsOn: 'F',
    valueRU: 'а',
    capsOnRU: 'А',
    row: 3,
    size: 's',
  },
  g: {
    position: 5,
    value: 'g',
    capsOn: 'G',
    valueRU: 'п',
    capsOnRU: 'П',
    row: 3,
    size: 's',
  },
  h: {
    position: 6,
    value: 'h',
    capsOn: 'H',
    valueRU: 'р',
    capsOnRU: 'Р',
    row: 3,
    size: 's',
  },
  j: {
    position: 7,
    value: 'j',
    capsOn: 'J',
    valueRU: 'о',
    capsOnRU: 'О',
    row: 3,
    size: 's',
  },
  k: {
    position: 8,
    value: 'k',
    capsOn: 'K',
    valueRU: 'л',
    capsOnRU: 'Л',
    row: 3,
    size: 's',
  },
  l: {
    position: 9,
    value: 'l',
    capsOn: 'L',
    valueRU: 'д',
    capsOnRU: 'Д',
    row: 3,
    size: 's',
  },
  semicolon: {
    position: 10,
    value: ';',
    shiftOn: ':',
    valueRU: 'ж',
    capsOnRU: 'Ж',
    row: 3,
    size: 's',
  },
  apostrophe: {
    position: 11,
    value: "'",
    shiftOn: ':',
    valueRU: 'э',
    capsOnRU: 'Э',
    row: 3,
    size: 's',
  },
  enter: {
    position: 12,
    value: 'enter',
    row: 3,
    size: 'l',
  },
  shift_left: {
    position: 0,
    value: 'shift',
    row: 4,
    size: 'l',
  },
  z: {
    position: 1,
    value: 'z',
    capsOn: 'Z',
    valueRU: 'я',
    capsOnRU: 'Я',
    row: 4,
    size: 's',
  },
  x: {
    position: 2,
    value: 'x',
    capsOn: 'X',
    valueRU: 'ч',
    capsOnRU: 'Ч',
    row: 4,
    size: 's',
  },
  c: {
    position: 3,
    value: 'c',
    capsOn: 'C',
    valueRU: 'с',
    capsOnRU: 'С',
    row: 4,
    size: 's',
  },
  v: {
    position: 4,
    value: 'v',
    capsOn: 'V',
    valueRU: 'м',
    capsOnRU: 'М',
    row: 4,
    size: 's',
  },
  b: {
    position: 5,
    value: 'b',
    capsOn: 'B',
    valueRU: 'и',
    capsOnRU: 'И',
    row: 4,
    size: 's',
  },
  n: {
    position: 6,
    value: 'n',
    capsOn: 'N',
    valueRU: 'т',
    capsOnRU: 'Т',
    row: 4,
    size: 's',
  },
  m: {
    position: 7,
    value: 'm',
    capsOn: 'M',
    valueRU: 'ь',
    capsOnRU: 'Ь',
    row: 4,
    size: 's',
  },
  comma: {
    position: 8,
    value: ',',
    shiftOn: '<',
    valueRU: 'б',
    capsOnRU: 'Б',
    row: 4,
    size: 's',
  },
  fullstop: {
    position: 9,
    value: '.',
    shiftOn: '>',
    valueRU: 'ю',
    capsOnRU: 'Ю',
    row: 4,
    size: 's',
  },
  question: {
    position: 10,
    value: '/',
    shiftOn: '?',
    valueRU: '.',
    capsOnRU: ',',
    row: 4,
    size: 's',
  },
  arrow_up: {
    position: 11,
    value: '▲',
    row: 4,
    size: 's',
    color: 'light'
  },
  shift_right: {
    position: 12,
    value: 'shift',
    row: 4,
    size: 'l',
  },
  ctrl_left: {
    position: 0,
    value: 'ctrl',
    row: 5,
    size: 's',
  },
  win: {
    position: 1,
    value: 'win',
    row: 5,
    size: 's',
  },
  alt_left: {
    position: 2,
    value: 'alt',
    row: 5,
    size: 's',
  },
  space: {
    position: 3,
    value: '',
    row: 5,
    size: 'xl',
  },
  alt_right: {
    position: 4,
    value: 'alt',
    row: 5,
    size: 's',
  },
  arrow_left: {
    position: 5,
    value: '◀',
    row: 5,
    size: 's',
    color: 'light'
  },
  arrow_down: {
    position: 6,
    value: '▼',
    row: 5,
    size: 's',
    color: 'light'
  },
  arrow_right: {
    position: 7,
    value: '▶',
    row: 5,
    size: 's',
    color: 'light'
  },
  ctrl_right: {
    position: 8,
    value: 'ctrl',
    row: 5,
    size: 's',
  },
};

export {
  keys,
  pageElements,
  textContent
};
